services:
  nerdinzzz-bot:
    image: ghcr.io/duckinzzz/nerdinzzz-bot:latest
    container_name: nerdinzzz-bot
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.20
    networks:
      - caddy-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      caddy: webhook.duckinzzz.ru/nerdinzzz
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.import: error_catch

networks:
  caddy-proxy:
    external: true