{
 "title": "Main dash",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "LLM question",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nerdinzzz-bot\"} | json request_type = `llm_question`"
    }
   ]
  },
  {
   "title": "Image generaion",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nerdinzzz-bot\"} | json request_type = `llm_question`"
    }
   ]
  },
  {
   "title": "Voice to text",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nerdinzzz-bot\"} | json request_type = `llm_question`"
    }
   ]
  },
  {
   "title": "Image to text",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nerdinzzz-bot\"} | json request_type = `llm_question`"
    }
   ]
  },
  {
   "title": "LLM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"nerdinzzz-bot\"}|= \"llm_response\"[$__auto])"
    }
   ]
  },
  {
   "title": "TTI usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"nerdinzzz-bot\"}|= \"image_generation\"[$__auto])"
    }
   ]
  },
  {
   "title": "STT usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"nerdinzzz-bot\"}|= \"stt_response\"[$__auto])"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"nerdinzzz-bot\"}| json | level = `error`"
    }
   ]
  }
 ]
}